### ISSUE TITLE
Why did you create it ? 

### ISSUE THREAD

**Issue by sotayamashita** [paulkoegel/redux-offline-docs#5]
original redux docs is generated by gitbook so you can read it offline by building docs on your computer with gitbook.

**Comment by paulkoegel** [comment]
this repo offers PDF, mobi, and ePub versions for people who don't want to build these themselves (e.g. because they don't want to set up Calibre).

it turns out that gitbook offers building offline versions automatically for free. we're currently preparing a gitbook version with PDF/epub/mobi files running under @rackt / @gaearon's account.
here is one running under my gitbook account: https://www.gitbook.com/book/paulkogel/redux-docs/details

for more details see discussion here: https://github.com/gaearon/gitbook-plugin-prism/issues/4#issuecomment-146348568

**Comment by sotayamashita** [comment]
I understood. Thanks for your quick reply

I use redux on my projects so I would like to help. Please let me know if you need help
